### ISSUE TITLE
Do not crash on empty lines in the middle of the diff

### ISSUE THREAD

**Issue by seletskiy** [seletskiy/ash#19]

**Comment by kovetskiy** [comment]
Please fix this in godiff package, **it's really necessary**, ash deletes comments.

**Comment by kovetskiy** [comment]
@seletskiy fix this

**Comment by seletskiy** [comment]
Now ash will stop if it encounters invalid diff (linked godiff commit: seletskiy/godiff@546bb41ee2b00497fe833b1a85da067c7ee1dd7).

It's not valid behaviour for diff parsing library for parsing invalid diffs (and broken in that way diff are invalid). It's very difficult to add workaround for heuristically determining where newline is just a mistake and when it's split between two diffs in one file, because there are some cornercases which are requires godiff parsing library to have some kind of "stash" for looking forward next lines until it will be able to make correct choice.
