### ISSUE TITLE
Compilation error on go get

### ISSUE THREAD

**Issue by dreamer-dead** [seletskiy/ash#26]
Error is

$ go get github.com/seletskiy/ash
# github.com/seletskiy/ash
../gocode/src/github.com/seletskiy/ash/activity.go:176: cannot use func literal (type func(*godiff.Diff, *godiff.Hunk, *godiff.Segment, *godiff.Line)) as type func(*godiff.Diff, *godiff.Hunk, *godiff.Segment, *godiff.Line) error in argument to value.Diff.ForEachLine
../gocode/src/github.com/seletskiy/ash/pr.go:104: cannot use func literal (type func(*godiff.Diff, *godiff.Hunk, *godiff.Segment, *godiff.Line)) as type func(*godiff.Diff, *godiff.Hunk, *godiff.Segment, *godiff.Line) error in argument to result.ForEachLine

Could you fix it please?

My go is
$ go version
go version go1.5.1 darwin/amd64

Thanks in advance!

**Comment by kovetskiy** [comment]
https://github.com/seletskiy/ash/pull/27
